[143] - Block negative slippage
gnosis/gp-swap-ui pull request #157
Opened 2021-02-18 17:45 UTC by W3stside

Closes #143 

Handles/disables entering negative slippage

2021-02-18 18:20 UTC, anxolin reviewed
Can you point out what was the fix? I'm lost. almost 300 lines, which part of `src/custom/components/TransactionSettings/index.tsx` is ours?

2021-02-18 18:59 UTC, W3stside commented
> Can you point out what was the fix? I'm lost. almost 300 lines, which part of `src/custom/components/TransactionSettings/index.tsx` is ours?

you gotta find it :mag:

2021-02-18 19:00 UTC, W3stside commented
> Can you point out what was the fix? I'm lost. almost 300 lines, which part of `src/custom/components/TransactionSettings/index.tsx` is ours?

https://github.com/gnosis/gp-swap-ui/blob/0b8743d24b431d06c8528c95dc37013c48d1f6e5/src/custom/components/TransactionSettings/index.tsx#L53

2021-02-18 19:11 UTC, alfetopito approved these changes
Awesome, it works.
For benchmark, I tried https://app.uniswap.org/#/swap and can reproduce the error there :D

Not related to this issue, but the UI is a bit off
![screenshot_2021-02-18_11-08-44](https://user-images.githubusercontent.com/43217/108408497-f3f9ac00-71d9-11eb-9280-fe6e9e12333f.png)

Not for this PR, just raising the point

2021-02-19 16:30 UTC, anxolin requested changes
I think we shouldn't duplicate all this code for just this line
Ideally, it should be easy to know what we have changed

Also, the Mod version doesn't compare line by line. You deleted lot's of things:
![image](https://user-images.githubusercontent.com/2352112/108532314-02c68880-72d8-11eb-80f0-6faec7f5d25e.png)


Please, review the rules we follow for overriding in our document.

2021-02-19 16:30 UTC, anxolin commented on src/custom/components/TransactionSettings/index.tsx
> +import React, { useState, useRef, useContext } from 'react'
This is too big of a copy paste for such a small change

2021-02-22 09:12 UTC, anxolin commented
Please, david consider this https://github.com/gnosis/gp-swap-ui/pull/166

2021-02-22 09:59 UTC, W3stside commented
closing in favour of #166

2021-02-22 09:59 UTC, closed without merging