Add twitter link.
gnosis/gp-swap-ui pull request #664
Opened 2021-05-20 16:26 UTC by biocom

This adds a Twitter icon/link in the header.

<img width="1066" alt="Screen Shot 2021-05-20 at 18 25 31" src="https://user-images.githubusercontent.com/31534717/119014970-c5d26680-b998-11eb-9ab7-e49fde756a3c.png">
<img width="375" alt="Screen Shot 2021-05-20 at 18 25 45" src="https://user-images.githubusercontent.com/31534717/119015004-ce2aa180-b998-11eb-881d-378ca57f5f0d.png">

2021-05-20 16:32 UTC, anxolin approved these changes

2021-05-20 18:02 UTC, alfetopito requested changes

2021-05-20 18:02 UTC, alfetopito commented on src/custom/components/Header/index.tsx
> +          </TwitterLink>
Build failure:

![screenshot_2021-05-20_11-01-53](https://user-images.githubusercontent.com/43217/119027028-b92f1d80-b95a-11eb-9b52-e733efcec65f.png)

2021-05-20 19:50 UTC, biocom commented on src/custom/components/Header/index.tsx
> +          </TwitterLink>
Had a hunch my empty <a href> would fail :) My bad...fixed now!

2021-05-20 19:58 UTC, alfetopito approved these changes
:bird: :musical_note:

2021-05-21 07:34 UTC, anxolin approved these changes
Nice. As a nit pick, could we add the cursor animation on hover?

<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia0.giphy.com%2Fmedia%2FSMKiEh9WDO6ze%2Fgiphy.gif&token=twitt" data-gitmeme-token="twitt"><img src="https://media0.giphy.com/media/SMKiEh9WDO6ze/giphy.gif" title="Created by gitme.me with /twitt"/></a>

2021-05-21 09:26 UTC, biocom commented
@anxolin Haha, sure, added :)

2021-05-21 10:23 UTC, anxolin approved these changes

2021-05-24 08:55 UTC, W3stside approved these changes

2021-05-26 12:20 UTC, anxolin commented
@Mergifyio refresh

2021-05-26 13:25 UTC, merged